//proposal
export const PROPOSAL_CHANGE_STEP = 'PROPOSAL_CHANGE_STEP';
export const PROPOSAL_CHANGE_SUCCESS = 'PROPOSAL_CHANGE_SUCCESS';
export const PROPOSAL_FORM_SHOW = "PROPOSAL_FORM_SHOW";
export const PROPOSAL_FORM_HIDE = "PROPOSAL_FORM_HIDE";
//popup
export const POPUP_SHOW = 'POPUP_SHOW';
export const POPUP_HIDE = 'POPUP_HIDE';
//partners
export const ADD_PARTNER = "ADD_PARTNER";
export const SHOW_ALL_PARTNERS = "SHOW_ALL_PARTNERS";
//question form
export const BOOL_TRUE = "BOOLEAN_ACTIONS_TRUE";
export const BOOL_FALSE = "BOOLEAN_ACTIONS_FALSE";